/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.omerucel.p2p.simple;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author omer
 */
public class WindowStart extends javax.swing.JFrame {

    private static WindowStart instance;

    public static WindowStart getInstance()
    {
        if (instance == null)
            instance = new WindowStart();

        return instance;
    }

    /**
     * Creates new form WindowStart
     */
    public WindowStart() {
        initComponents();
    }

    public int getSelectedMode()
    {
        return jComboBox1.getSelectedIndex();
    }

    private void showLoading(Boolean status)
    {
        if (status)
        {
            jComboBox1.setEnabled(false);
            jTextField1.setEnabled(false);
            jButton3.setEnabled(false);
        }else{
            jComboBox1.setEnabled(true);
            jTextField1.setEnabled(true);
            jButton3.setEnabled(true);
        }
    }

    public void showInformation(String message)
    {
        JOptionPane.showMessageDialog(this, message);
    }

    public class OnServerStartingFailed implements CommandAbstract.Command
    {

        public void execute(Object data) {
            WindowStart.getInstance().showLoading(false);
            WindowStart.getInstance().showInformation("Sunucu başlatılamadı.");
        }
    }

    public class OnServerStarted implements CommandAbstract.Command
    {

        public void execute(Object data)
        {
            if ( WindowStart.getInstance().getSelectedMode() == 1)
            {
                Client client = new Client(jTextField1.getText());
                client.on("connection-failed", new OnClientConnectionFailed());
                client.on("connected", new OnClientConnected());
                client.on("response-search", new WindowClient.OnResponseSearch());
                client.on("response-welcome", new WindowClient.OnResponseWelcome());
                ClientFactory.setMainServerClient(client);
                new Thread(client).start();
            }else{
                WindowStart.getInstance().setVisible(false);
                WindowMainServer.getInstance().setVisible(true);
                Server.getInstance().setWindow(WindowMainServer.getInstance());
            }
        }
        
    }

    public class OnClientConnectionFailed implements CommandAbstract.Command
    {
        public void execute(Object data)
        {
            WindowStart.getInstance().showLoading(false);
            WindowStart.getInstance().showInformation("Sunucuya bağlanılamadı.");
        }
    }

    public class OnClientConnected implements CommandAbstract.Command
    {
        public void execute(Object data)
        {
            WindowStart.getInstance().setVisible(false);
            WindowClient.getInstance().setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Sunucu IP Adresi");

        jTextField1.setEditable(false);

        jButton3.setText("Başlat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Çalışma Modu");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ana Sunucu", "İstemci" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButton3))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel3))
                        .add(41, 41, 41)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField1)
                            .add(jComboBox1, 0, 217, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        if (jComboBox1.getSelectedIndex() == 0)
        {
            jTextField1.setEditable(false);
        }else{
            jTextField1.setEditable(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.showLoading(true);

        if (jComboBox1.getSelectedIndex() == 0)
        {
            Server.getInstance().setMode(Server.MAIN_SERVER);
        }else{
            Server.getInstance().setMode(Server.CLIENT);
        }

        Server.getInstance().on("starting-failed", new OnServerStartingFailed());
        Server.getInstance().on("started", new OnServerStarted());
        new Thread(Server.getInstance()).start();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
