/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p2p;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import p2p.socket.FileServerConnection;

/**
 *
 * @author omer
 */
public class DialogClientSelect extends javax.swing.JDialog {

    private DefaultTableModel clientTableModel;
    private String fileHash;

    /**
     * Creates new form DialogClientSelect
     */
    public DialogClientSelect(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        clientTableModel = new DefaultTableModel();
        clientTableModel.addColumn("IP");
        clientTableModel.addColumn("Port");
        clientTable.setModel(clientTableModel);

        setLocationRelativeTo(null);
    }

    public void loadClients(String fileHash, ArrayList<Map> fileClients)
    {
        this.fileHash = fileHash;
        for(int i = 0; i < clientTableModel.getRowCount(); i++)
            clientTableModel.removeRow(i);

        for(Map map : fileClients)
        {
            clientTableModel.addRow(new Object[]{
                map.get("ip").toString(),
                map.get("port").toString()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(clientTable);

        jButton1.setText("İndir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("İptal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (clientTable.getSelectedRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this, "En az bir istemci seçmelisiniz!");
        }else{
            DialogLoading.getInstance().toggle(true);
            WindowClient windowClient = (WindowClient)getParent();

            int[] indexes = clientTable.getSelectedRows();
            ArrayList<Map> clients = new ArrayList<Map>();
            for(int i : indexes)
            {
                String host = clientTableModel.getValueAt(i, 0).toString();
                int port = Integer.parseInt(clientTableModel.getValueAt(i, 1).toString());

                Map temp = new LinkedHashMap();
                temp.put("host", host);
                temp.put("port", port);
                clients.add(temp);
            }
            DialogLoading.getInstance().toggle(false);
            try {
                windowClient.getDownloadManager().downloadFile(fileHash, clients);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Dosya indirme işlemi hazırlanırken bir sorun oluştu.");
            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
