/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p2p;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omer
 */
public class WindowMainServer extends WindowAbstract {

    private static WindowMainServer instance = null;
    DefaultTableModel clientsTableModel;
    DefaultTableModel filesTableModel;

    public static WindowMainServer getInstance()
    {
        if (instance == null)
            instance = new WindowMainServer();

        return instance;
    }

    /**
     * Creates new form WindowMainServer
     */
    public WindowMainServer() {
        initComponents();

        filesTableModel = new DefaultTableModel();
        filesTableModel.addColumn("Hash");
        filesTableModel.addColumn("Dosya Türü");
        filesTableModel.addColumn("Dosya Boyutu");
        filesTableModel.addColumn("Eş Sayısı");
        filesTable.setModel(filesTableModel);

        clientsTableModel = new DefaultTableModel();
        clientsTableModel.addColumn("Hash");
        clientsTableModel.addColumn("IP");
        clientsTableModel.addColumn("Sunucu Portu");
        clientsTable.setModel(clientsTableModel);

        setLocationRelativeTo(null);
    }

    public void clearClientTable()
    {
        for(int i = 0; i < clientsTableModel.getRowCount(); i++)
            clientsTableModel.removeRow(i);
    }

    public void addClient(String hash, String ip)
    {
        clientsTableModel.addRow(new Object[]{hash, ip, 0});
    }

    public void removeClient(String hash)
    {
        for(int i = 0; i < clientsTableModel.getRowCount(); i++)
        {
            if (clientsTableModel.getValueAt(i, 0).equals(hash))
            {
                clientsTableModel.removeRow(i);
                break;
            }
        }
    }

    public void updateClientServerPort(String hash, int serverPort)
    {
        for(int i = 0; i < clientsTableModel.getRowCount(); i++)
        {
            if (clientsTableModel.getValueAt(i, 0).equals(hash))
            {
                clientsTableModel.setValueAt(serverPort, i, 2);
                break;
            }
        }
    }

    public void addFile(String hash, String fileType, int size, int peerCount)
    {
        for(int i = 0; i < filesTableModel.getRowCount(); i++)
        {
            if (filesTableModel.getValueAt(i, 0).equals(hash))
            {
                filesTableModel.setValueAt(fileType, i, 1);
                filesTableModel.setValueAt(peerCount, i, 3);
                return;
            }
        }

        filesTableModel.addRow(new Object[]{hash, fileType, size, peerCount});
    }

    public void removeFile(String hash, int peerCount)
    {
        for(int i = 0; i < filesTableModel.getRowCount(); i++)
        {
            if (filesTableModel.getValueAt(i, 0).equals(hash))
            {
                if (peerCount == 0)
                {
                    filesTableModel.removeRow(i);
                }else{
                    filesTableModel.setValueAt(peerCount, i, 3);
                }
                return;
            }
        }
    }

    public void addLog(String message)
    {
        jTextArea1.setText(jTextArea1.getText() + message + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        filesTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Log", jPanel1);

        filesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(filesTable);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dosyalar", jPanel2);

        clientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(clientsTable);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("İstemciler", jPanel3);

        jButton1.setText("Sunucuyu Kapat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTabbedPane1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogLoading.getInstance().toggle(true);
        ObjectContainer.getMainServer().stop();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientsTable;
    private javax.swing.JTable filesTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
