/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p2p;

import java.io.File;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import p2p.socket.RequestFileClients;

/**
 *
 * @author omer
 */
public class WindowClient extends WindowAbstract {

    private static WindowClient instance;
    SearchManager searchManager;
    ShareManager shareManager;
    DownloadManager downloadManager;
    DefaultTableModel downloadTableModel;
    DefaultTableModel searchTableModel;
    DefaultTableModel shareTableModel;

    public static WindowClient getInstance()
    {
        if (instance == null)
            instance = new WindowClient();

        return instance;
    }


    /**
     * Creates new form WindowClient
     */
    private WindowClient() {
        initComponents();

        downloadTableModel = new DefaultTableModel();
        downloadTableModel.addColumn("Hash");
        downloadTableModel.addColumn("Adı");
        downloadTableModel.addColumn("Türü");
        downloadTableModel.addColumn("Boyutu");
        downloadTableModel.addColumn("Bağlanılan Eş Sayısı");
        downloadTableModel.addColumn("İndirilen Parça");
        downloadTableModel.addColumn("Kalan Parça");
        downloadTableModel.addColumn("Toplam Parça");
        downloadTable.setModel(downloadTableModel);

        searchTableModel = new DefaultTableModel();
        searchTableModel.addColumn("Hash");
        searchTableModel.addColumn("Adı");
        searchTableModel.addColumn("Türü");
        searchTableModel.addColumn("Boyutu");
        searchTableModel.addColumn("Eş Sayısı");
        searchTable.setModel(searchTableModel);

        shareTableModel = new DefaultTableModel();
        shareTableModel.addColumn("Hash");
        shareTableModel.addColumn("Adı");
        shareTableModel.addColumn("Türü");
        shareTableModel.addColumn("Boyutu");
        shareTableModel.addColumn("Dosya Yolu");
        shareTable.setModel(shareTableModel);

        setLocationRelativeTo(null);

        shareTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        downloadTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        searchTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        searchManager = new SearchManager(this);
        shareManager = new ShareManager(this);
        downloadManager = new DownloadManager(this);
    }

    public SearchManager getSearchManager()
    {
        return searchManager;
    }

    public ShareManager getShareManager()
    {
        return shareManager;
    }

    public DownloadManager getDownloadManager()
    {
        return downloadManager;
    }

    public JTable getSearchTable()
    {
        return searchTable;
    }

    public JTable getShareTable()
    {
        return shareTable;
    }

    public JTable getDownloadTable()
    {
        return downloadTable;
    }

    public DefaultTableModel getSearchTableModel()
    {
        return searchTableModel;
    }

    public DefaultTableModel getShareTableModel()
    {
        return shareTableModel;
    }

    public DefaultTableModel getDownloadTableModel()
    {
        return downloadTableModel;
    }

    public JTextField getSearchBox()
    {
        return searchBox;
    }

    public JTextArea getDownloadLog()
    {
        return downloadLog;
    }

    public void focusTab(int index)
    {
        jTabbedPane1.setSelectedIndex(index);
    }

    public void reset()
    {
        downloadManager.clear();
        shareManager.clear();
        searchManager.clear();
    }

    public void showClientSelectDialog(String fileHash, ArrayList<Map> fileClients)
    {
        DialogLoading.getInstance().toggle(false);

        DialogClientSelect dialogClientSelect = new DialogClientSelect(this, true);
        dialogClientSelect.loadClients(fileHash, fileClients);
        dialogClientSelect.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        downloadTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        downloadLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        searchBox = new javax.swing.JTextField();
        downloadButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        dosyaEkle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        shareTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        exitButton.setText("Bağlantıyı Kapat");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        downloadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(downloadTable);

        downloadLog.setEditable(false);
        downloadLog.setColumns(20);
        downloadLog.setRows(5);
        jScrollPane4.setViewportView(downloadLog);

        jLabel1.setText("Log");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .add(jScrollPane4)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel1)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .add(2, 2, 2)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("İndirilenler", jPanel1);

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(searchTable);

        searchButton.setText("Ara");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        downloadButton.setText("Seçili Dosyayı İndir");
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(searchBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(searchButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(downloadButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchButton)
                    .add(searchBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(downloadButton))
        );

        jTabbedPane1.addTab("Dosya Ara", jPanel2);

        dosyaEkle.setText("Dosya Ekle");
        dosyaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaEkleActionPerformed(evt);
            }
        });

        shareTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(shareTable);

        jButton1.setText("Paylaşımı Kaldır");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, dosyaEkle)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(dosyaEkle)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Paylaşılan Dosyalar", jPanel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(exitButton))
                    .add(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(exitButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

        DialogLoading.getInstance().toggle(true);
        ObjectContainer.getMainServerConnection().disconnect();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void dosyaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaEkleActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(true);

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            File[] selectedFiles = fc.getSelectedFiles();

            shareManager.addFiles(selectedFiles);
        }
    }//GEN-LAST:event_dosyaEkleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        shareManager.removeFiles();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        DialogLoading.getInstance().toggle(true);
        searchManager.search();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed

        DialogLoading.getInstance().toggle(true);
        int selectedIndex = searchTable.getSelectedRow();
        if (selectedIndex < 0)
        {
            DialogLoading.getInstance().toggle(false);
            showErrorMessage("Lütfen bir dosya seçiniz!");
            return;
        }

        String hash = searchTableModel.getValueAt(selectedIndex, 0).toString();

        if (!searchManager.hasFile(hash))
        {
            DialogLoading.getInstance().toggle(false);
            showErrorMessage("Lütfen bir dosya seçiniz!");
            return;
        }

        if (shareManager.hasFile(hash))
        {
            DialogLoading.getInstance().toggle(false);
            showErrorMessage("Bu dosyayı zaten paylaşmaktasınız!");
            return;
        }

        if (downloadManager.hasFile(hash))
        {
            DialogLoading.getInstance().toggle(false);
            showErrorMessage("Bu dosyayı zaten indiriyorsunuz!");
            return;
        }

        RequestFileClients requestFileClients = new RequestFileClients(hash);

        ObjectContainer.getMainServerConnection().writeObject(requestFileClients);
    }//GEN-LAST:event_downloadButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dosyaEkle;
    private javax.swing.JButton downloadButton;
    private javax.swing.JTextArea downloadLog;
    private javax.swing.JTable downloadTable;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable searchTable;
    private javax.swing.JTable shareTable;
    // End of variables declaration//GEN-END:variables
}
